spring.application.name=GymApp
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/gym
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8282
logging.level.org.springframework.security=DEBUG
file.upload-dir=C:\\Users\\dchatzop\\Downloads
file.dest-dir=C:\\Users\\dchatzop\\Front-end\\gym-frontend\\src\\pages\\customer\\photos\\athletePhotos

twilio.accountSid=ACd2c8b8550b126377cefbcaf4f2cd8c20
twilio.authToken=87eeb501ff18842733861c62f5495611
twilio.trialNumber=+12084358829